#a demo docker compose file

router:
  build: .
  links:
  - router2:php
  - router2:nginx
  ports:
  - 80:80
  - 443:443
  environment:
  - OPG_NGINX_ROUTER_00_VHOST=php.*
  - OPG_NGINX_ROUTER_00_TARGET=http://php
  - OPG_NGINX_ROUTER_00_CLIENT_MAX_BODY_SIZE=20M
  - OPG_NGINX_ROUTER_01_VHOST=nginx.*
  - OPG_NGINX_ROUTER_01_TARGET=https://nginx

router2:
  build: .
  links:
  - php
  - nginx
  environment:
  - OPG_NGINX_ROUTER_00_VHOST=php.*
  - OPG_NGINX_ROUTER_00_TARGET=http://php
  - OPG_NGINX_ROUTER_00_CLIENT_MAX_BODY_SIZE=20M
  - OPG_NGINX_ROUTER_01_VHOST=nginx.*
  - OPG_NGINX_ROUTER_01_TARGET=https://nginx


php:
  image: registry.service.dsd.io/opguk/php-fpm


nginx:
  image: registry.service.dsd.io/opguk/nginx

