elasticsearchshareddata:
  build: .

kibana:
  image: registry.service.opg.digital/opguk/kibana:latest
  environment:
    ELASTICSEARCH: elasticsearch
    ELASTICSEARCH_PORT_9200_TCP: 9200
  ports:
    - 5601:5601
  links:
    - elasticsearch

elasticsearch:
  image: registry.service.opg.digital/opguk/elasticsearch5:latest
  ports:
    - 9200:9200
    - 9300:9300
  environment:
    SHARED_DATA_BASE: /tmp
    SHARED_DATA_PATHS: "['/elasticsearchshareddata/beats']"
    DASHBOARD_SLEEP_TIMEOUT: 90
  volumes:
    - /tmp/elasticsearchshareddata
  volumes_from:
    - elasticsearchshareddata